// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6xKqgca3-Qh1dhFTS2635aM5MUCUQOzo',
    appId: '1:418877438280:web:e5fc18cc7a0244acbc1b7d',
    messagingSenderId: '418877438280',
    projectId: 'online-order-e232c',
    authDomain: 'online-order-e232c.firebaseapp.com',
    storageBucket: 'online-order-e232c.appspot.com',
    measurementId: 'G-5FLFW7WDYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ee4WPn7wIbxSBWYIX65nhXEB4SwfN-E',
    appId: '1:418877438280:android:9e90162442fa2504bc1b7d',
    messagingSenderId: '418877438280',
    projectId: 'online-order-e232c',
    storageBucket: 'online-order-e232c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwWdA46EyZfgxKo09v70KRV-Bwn3_elaA',
    appId: '1:418877438280:ios:8ba44fcf1972a445bc1b7d',
    messagingSenderId: '418877438280',
    projectId: 'online-order-e232c',
    storageBucket: 'online-order-e232c.appspot.com',
    iosClientId: '418877438280-lha9lj6ssjd1uv0b8kkpg1311k9g4ibj.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwWdA46EyZfgxKo09v70KRV-Bwn3_elaA',
    appId: '1:418877438280:ios:8ba44fcf1972a445bc1b7d',
    messagingSenderId: '418877438280',
    projectId: 'online-order-e232c',
    storageBucket: 'online-order-e232c.appspot.com',
    iosClientId: '418877438280-lha9lj6ssjd1uv0b8kkpg1311k9g4ibj.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineOrder',
  );
}
